### ISSUE TITLE
Deprecation of Python 2 compatibility?

### ISSUE THREAD

**Issue by JanKoppe** [opencast/pyCA#153]
How are we standing on supporting compatibility to Python 2 in the future? EOL is in about 1.5 years (https://mail.python.org/pipermail/python-dev/2018-March/152348.html), and afaik most distributions have Python 3 available, if not already as default. So I don't think that there is a realistic need for py2 compatibility anymore.

I'm not suggesting to immediately drop support and rip out compatibllity code, but when the time comes where there is a non-trivial amount of work to ensure py2 compat., being able to ignore py2 would probably be nice.

**Comment by lkiesow** [comment]
If it's really necessary we can always talk about it. I'm not set on Python 2. I mostly use Python 3 nowadays anyway and the only places where I use Python 2 is, where it is set as default and I don't bother to explicitly call Python 3.

That said, it is still the default on a lot of systems right now which is why I would not deliberately break compatibility right now if not for a good reason.

In any case, I suggest we add a notice that we will definitely drop Python 2 compatibility at the end of 2019?

**Comment by JanKoppe** [comment]
Seems reasonable. Notice in the readme should suffice.
