### ISSUE TITLE
Parallel video uploading\ingesting

### ISSUE THREAD

**Issue by yurket** [opencast/pyCA#17]
Have you considered this option? I think it could be very useful, when an internet connection is not fast enough to upload a video before the next recording starts.

**Comment by lkiesow** [comment]
The problem here is Matterhorn. The service oriented architecture requires that you send the mediapackage to the ingest service where the uploaded elements are added and the enriched mediapackage is returned. If you upload thin in parallel, you would hence end up with two states of a mediapackge. Though I think that with how Matterhorn handles things at the moment, in theory it would be possible to manually, it is not very practical to do so.

Especially if you consider that parallel ingest would usually not increase the speed things are uploaded. If the CA has a slow connection, a single upload should use up the whole bandwith already.

**Comment by lkiesow** [comment]
Just realized that you could also have meant that you want the upload and the recording in parallel. That would be possible. But if I remember correctly, it caused some problems with the reference CA in the past where the upload would decrease the performance so that the recording failed in some cases.

But another option would be to delay the ingest until there is more time for it. E.g. require a time of 15min without scheduled event before starting the media file upload.

**Comment by yurket** [comment]
yes, I want to upload the previous video while the new one is recording. I think, I need to run some tests and represent the results. For example it would be interesting to record a long video (30mins - 1hour) and to look how long it will take to upload it to Matterhorn with my internet connection.

**Comment by JanKoppe** [comment]
This has been solved with #56
